services:
  - type: web
    name: neoarcana
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_v2.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false